
const summery = {
    register:{
        url:'/api/v1/users/register',
        method:'post'
    },
    login:{
        url:'/api/v1/users/login',
        method:'post'
    },
    forgetPassword:{
        url:'/api/v1/users/forget-password',
        method:'post'
    },
    verifyOtp:{
        url:'/api/v1/users/verify-otp',
        method:'post'
    },
    resetPassword:{
        url:'/api/v1/users/reset-password',
        method:'put'
    },
    relogin:{
        url:'/api/v1/users/relogin',
        method:'post'
    },
    getCurrentUser:{
        url:'/api/v1/users/current-user',
        method:'get'
    },
    logoutUser:{
        url:'api/v1/users/logout',
        method:'put'
    },
    updateUserAvatar:{
        url:'/api/v1/users/update-avatar',
        method:'put'
    },
    updateUserDetails:{
        url:'/api/v1/users/update-user-details',
        method:'put'
    },
    uploadImage:{
        url:'/api/v1/upload',
        method:'post'
    },
    addCategory:{
        url:'/api/v1/category/add-category',
        method:'post'
    },
    getCategories:{
        url:'/api/v1/category/get-category',
        method:'get'
    },
    updateCategory:{
        url:'/api/v1/category/update-category',
        method:'put'
    },
    deleteCategory:{
        url:'/api/v1/category/delete-category',
        method:'post'
    },
    createSubCategory:{
        url:'/api/v1/sub-category/add',
        method:'post'
    },
    getSubCategory:{
        url:'/api/v1/sub-category/get',
        method:'get'
    },
    updateSubCategory:{
        url:'/api/v1/sub-category/update',
        method:'put'
    },
    deleteSubCategory:{
        url:'/api/v1/sub-category/delete',
        method:'delete'
    },
    addProduct:{
        url:'/api/v1/product/add',
        method:'post'
    },
    getProducts:{
        url:'/api/v1/product/get',
        method:'post'
    },
    getProductByCategory:{
        url:'/api/v1/product/get-product-by-category',
        method:'post'
    },
    getProductBySubCategory:{
        url:'/api/v1/product/get-product-by-subcategory',
        method:'post'
    },
    deleteProduct:{
        url:'/api/v1/product/delete',
        method:'delete'
    },
    updateProduct:{
        url:'/api/v1/product/update',
        method:'put'
    },
    getProductById:{
        url:'/api/v1/product/get-by-id',
        method:'post'
    },
    searchProduct:{
        url:'/api/v1/product/search',
        method:'post'
    },
    addToCart:{
        url:'/api/v1/cart/add',
        method:'post'
    },
    getCartItems:{
        url:'/api/v1/cart/get',
        method:'get'
    },
    updateCartItem:{
        url:'/api/v1/cart/update',
        method:'put'
    },
    deleteCartItem:{
        url:'/api/v1/cart/delete',
        method:'delete'
    },
    createAddress:{
        url:'/api/v1/address/add',
        method:'post'
    },
    getAddress:{
        url:'/api/v1/address/get',
        method:'get'
    },
    updateAddress:{
        url:'/api/v1/address/update',
        method:'put'
    },
    disableAddress:{
        url:'/api/v1/address/delete',
        method:'post'
    },
    createOrder:{
        url:'/api/v1/order/create',
        method:'post'
    },
    createPaymentOrder:{
        url:'/api/v1/order/create-payment-order',
        method:'post'
    }
}

export default summery;